[package]
name = "rust-cdc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0.0", features = ["full"] }
tokio-util = { version = "0.7.0", features = ["full"] }
bytes = { version = "1"}
bitflags = "1.3"
thiserror = "1.0.30"
memchr = { version = "2.4.1", default-features = false }
futures-core = { version = "0.3.19", default-features = false }
futures-util = { version = "0.3.19", default-features = false, features = ["alloc", "sink"] }
time = { version = "0.3.2", features = ["macros", "formatting", "parsing"], optional = true }

